name: Update Spheron Cluster Instance

on:
  push:
    branches:
      - main

jobs:
  update-spheron-instance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract version
        id: extract-version
        run: echo "version=$(cat version.json | jq -r '.version')" >> "$GITHUB_OUTPUT"

      - name: Print version
        run: echo ${{ steps.extract-version.outputs.version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./server/Dockerfile
          push: true
          tags: nft-minter-server:${{ steps.extract-version.outputs.version }}

      - name: Update Spheron Instance
        id: updating-instance
        # uses: decent-infra/shomix-car-update-action@v1.3
        uses: spheronFdn/instance-update-action@08fadded5b263743ba5a0af35dd3baae9a37079a
        with:
          spheron-token: ${{ secrets.SPHERON_TOKEN }}
          instance-id: "6466372002397f00124967ac"
          tag: ${{ steps.extract-version.outputs.version }}
          env: '[ "key1=value1", "key2=value2" ]'
          secret-env: '[ "skey1=svalue1", "skey2=svalue2" ]'
